# Generated by Django 4.2.16 on 2024-09-21 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('file_title', models.CharField()),
                ('file_origin_name', models.CharField()),
                ('file_link', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_login', models.CharField(max_length=40)),
                ('user_password', models.CharField(max_length=10)),
                ('status_admin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('files_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_cloud_storage.files')),
                ('users_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_cloud_storage.users')),
            ],
        ),
    ]
