# Generated by Django 5.1.1 on 2024-09-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cloud_storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_login',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_status_admin',
            field=models.BooleanField(default=False),
        ),
    ]
