# Generated by Django 5.1.1 on 2024-10-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cloud_storage', '0003_alter_files_id_alter_users_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='file_comment',
            field=models.TextField(default=''),
        ),
    ]
