# Generated by Django 5.1.1 on 2024-10-04 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cloud_storage', '0004_files_file_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['user_full_name'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
