# Generated by Django 5.1.1 on 2024-10-06 12:17

import app_cloud_storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cloud_storage', '0005_alter_users_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['full_name'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RenameField(
            model_name='files',
            old_name='file_comment',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='files',
            old_name='file_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='files',
            old_name='file_body',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='files',
            old_name='file_last_download',
            new_name='last_download',
        ),
        migrations.RenameField(
            model_name='files',
            old_name='file_link',
            new_name='origin_title',
        ),
        migrations.RenameField(
            model_name='files',
            old_name='file_origin_name',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='files',
            old_name='file_size',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='user_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='user_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='user_full_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='user_last_visit',
            new_name='last_visit',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='user_login',
            new_name='login',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='user_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='user_status_admin',
            new_name='status_admin',
        ),
        migrations.RemoveField(
            model_name='files',
            name='file_title',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_avatar',
        ),
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.ImageField(default='avatar-boy.svg', upload_to=app_cloud_storage.models.user_directory_path),
        ),
    ]
