# Generated by Django 5.1.1 on 2024-10-06 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cloud_storage', '0006_alter_users_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='origin_title',
        ),
    ]
