# Generated by Django 5.1.1 on 2024-10-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cloud_storage', '0007_remove_files_origin_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='users_id',
            new_name='user_id',
        ),
    ]
